name: Build the website
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build site
        run: bundle exec jekyll build
      - name: Upload site
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
          if-no-files-found: error
