name: CheckLinks
on:
  workflow_dispatch:
  pull_request:

jobs:
  checklinks:
    name: Check Links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build site
        run: bundle exec jekyll build
      - name: Install dependencies
        run: |
          gem install html-proofer
      - name: Check for broken links
        run: |
          htmlproofer --parallel "{'in_processes': 1}" ./_site &> links.log
        continue-on-error: true
      - name: Archive log links
        uses: actions/upload-artifact@v2
        with:
          name: links-check.log
          path: links.log

