name: CheckLinks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checklinks:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true
      - name: Install bundler
        run: sudo apt update -y && sudo apt install -y bundler
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-new-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: Install dependencies
        run: |
          bundle config path "$PWD/vendor/bundle"
          bundle install
      - name: Check for broken links
        run: |
          bundle exec htmlproofer --log-level :debug ./_site &> links.log
        continue-on-error: true
      - name: Archive log links
        uses: actions/upload-artifact@v1
        with:
          name: links-check.log
          path: links.log

